dist: trusty
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
    include:
        - php: 7.2
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    allow_failures:
        - php: nightly

install:
    - |
        if [[ "$TRAVIS_PHP_VERSION" == 'nightly' ]]; then
          travis_retry composer update --ignore-platform-reqs --no-interaction --prefer-dist
        else
          travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
        fi

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - printf '\n' | pecl install yaml

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
